added scikit-learn for the accuracy
ImportError: To be able to use accuracy, you need to install the following dependency: sklearn.
Please install it using 'pip install scikit-learn' for instance.